import type { NextPage } from 'next'
import { useEffect } from 'react'
import { useRouter } from 'next/router'
import Head from 'next/head'
import { useUser } from '@m3o/nextjs'
import { MainLayout } from '../components/MainLayout'

const ProtectedClient: NextPage = () => {
  const { user, isAuthenticating } = useUser()
  const router = useRouter()

  useEffect(() => {
    if (!isAuthenticating && !user) {
      router.push('/')
    }
  }, [isAuthenticating, user, router])

  return (
    <>
      <Head>
        <title>Test M3O Auth</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        {isAuthenticating ? (
          <p>Authenticating...</p>
        ) : user ? (
          'Authenticated'
        ) : null}
      </MainLayout>
    </>
  )
}

export default ProtectedClient
